
# Basic site information.
# TODO: You can change it to your information.

name: 空洽网
description: 人生不是要过的怎样，而是要懂得怎样去过。
meta_description: 人生不是要过的怎样，而是要懂得怎样去过。

logo: false
navigation: true
paginate: 15


# Less important changes below. (Code-highlighting, markdown)

highlighter: rouge
markdown: kramdown


# Feed!

feed:
  path: feed.xml


# However, pagination is important.

gems: [jekyll-paginate, rouge]


# This is for author page generation.

collections:
  authors: {output: true, permalink: '/authors/:path/'}
defaults:
- scope: {path: '', type: authors}
  values: {layout: author}


